version: '3.7'

services:
  database:
    container_name: diplomDB
    image: 'postgres'
    #    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  diplom:
    build: .
    links:
      - database
    #    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
    depends_on:
      - database